version: '3'

services:

  puzzles:
    image: puzzles
    container_name: puzzles
    build:
      context: "."
      dockerfile: "docker/dev/Dockerfile"
    ports:
      - 8200:8200
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: 172.16.0.2
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8200
      ALLOW_ORIGIN: https://puzzles.jounetsism.biz
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    volumes:
      - "./controllers:/app/controllers"
      - "./config:/app/config"
      - "./models:/app/models"
      - "./modules:/app/modules"
      - "./routes:/app/routes"
      - "./services:/app/services"
    networks:
      shared_network:
        ipv4_address: ${BACKEND_HOST}
    hostname: puzzles
    extra_hosts:
      - mysql:${DB_HOST}
    tty: true
    command: go run main.go watch

networks:
  shared_network:
    external: true